name: HSP Shop
favicon: null
layout_spectrum: 0.9988239058293402
typography_spectrum: 0.6835163796786219
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8194072965998203
  lightness: 0.9154568291269243
  saturation: 0.8078540924470872
  rhythmicContrast: 0.7164857548195869
purpose: []
